version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
      - ELASTIC_PASSWORD=stakatertest
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/aesdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - nordmart-services-network

  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - nordmart-services-network
  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nordmart-services-network
    depends_on:
      - zookeeper
  products-search:
    container_name: products-search
    build: .
    ports:
      - "8080:8080"
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: stakatertest
      KAFKA_ADDRESS: kafka
      KAFKA_PORT: 9092
    networks:
      - nordmart-services-network
    depends_on:
      - elasticsearch
      - kafka
networks:
  nordmart-services-network:
    driver: bridge