version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9200
      - ELASTIC_PASSWORD=stakatertest
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./data/aesdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - nordmart-services-network

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - nordmart-services-network
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - nordmart-services-network
  search:
    build:
      context: ./
      dockerfile: Dockerfile
    image: nordmart-products-search:snapshot
    ports:
      - "8080:8080"
    environment:
      ELASTICSEARCH_HOST: elasticsearch
      ELASTICSEARCH_PORT: 9200
      ELASTICSEARCH_USERNAME: elastic
      ELASTICSEARCH_PASSWORD: stakatertest
    networks:
      - nordmart-services-network
    depends_on:
      - elasticsearch
networks:
  nordmart-services-network:
    driver: bridge