application:
  applicationName: "search"
  configMap:
    enabled: true
    files:
    - nameSuffix: ""
      data:
        ELASTICSEARCH_USERNAME: elastic
        ELASTICSEARCH_HOST: "search-elasticsearch-es-http"
        ELASTICSEARCH_PORT: "9200"
        KAFKA_ADDRESS: "nordmart-kafka-bootstrap"
        KAFKA_PORT: "9092"
        JAEGER_ENDPOINT: "http://jaeger-collector.istio-system:14268/api/traces"
  deployment:
    additionalLabels:
      appCategory: "backend"
    annotations:
    podLabels:
    volumes: {}
    resources: 
      limits:
        memory: 1Gi 
        cpu: 0.5
      requests:
        memory: 128Mi
        cpu: 0.1
    imagePullSecrets: nexus-docker-config-forked
    image:
      repository: stakater/stakater-nordmart-search
      tag: v0.0.1
    envFrom:
    - type: configmap
      name: ""    
    env:
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: search-elasticsearch-es-elastic-user
          key: elastic
    probes:
      readinessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
      livenessProbe:
        failureThreshold: 3
        periodSeconds: 60
        successThreshold: 1
        timeoutSeconds: 1
        initialDelaySeconds: 10
        httpGet:
          path: /actuator/health
          port: 8080
  service:
    ports:
    - port: 8080
      name: https
      targetPort: 8080
  rbac:
    create: false
    serviceAccount:
      name: default

  
