##### nordmart search application

applicationName: search
labels:
  group: com.stakater
  team: nordmart
# Deployment parameters
deployment:
  replicas: 2
  strategy:
    type: RollingUpdate
  podLabels: []
  # Image location
  image:
    repository: "DOCKER_REPOSITORY_URL"
    tag: IMAGE_TAG
  # Image pull secret  
  imagePullSecrets: "nexus-secret"  
  # Resource request and limits
  resources:
    limits:
      memory: 1Gi
      cpu: 0.3
    requests:
      memory: 500Mi
      cpu: 0.1
  # Probes for liveness and readiness
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 150
      httpGet:
        path: /actuator/health
        port: 8080
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 20
      successThreshold: 1
      timeoutSeconds: 5
      initialDelaySeconds: 150
      httpGet:
        path: /actuator/health
        port: 8080
  # Environment variables 
  env:
    - name: ELASTICSEARCH_HOST
      value: "elasticsearch-svc"
    - name: ELASTICSEARCH_PORT
      value: "9200"
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-secret
          key: elasticsearch_password
    - name: KAFKA_ADDRESS
      value: "kafka-cluster-kafka-bootstrap"
    - name: KAFKA_PORT
      value: "9092"
  volumes: []
  volumeMounts: []
  securityContext: []
  
# Role Based Access Control
rbac:
  enabled: true
  serviceAccount:
    enabled: true

# Service configuration
service:
  ports:
  - port: 8080
    name: http
    targetPort: 8080

# Openshift Routes
route:
  enabled: true
  annotations: []
  additionalLabels: 
    router: default
  port:
    targetPort: http
  wildcardPolicy: None
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect

##### elasticsearch

