applicationName: "search"
deployment:
  podLabels:
    app: search
  image:
    repository: docker.release.stakater.com:443/stakater/search
    tag: v0.0.2
  imagePullSecrets: "docker-registry-nexus-secret"
  env:
    - name: ELASTICSEARCH_PASSWORD
      valueFrom:
        secretKeyRef:
          name: elasticsearch-secret
          key: elasticsearch_password

    - name: ELASTICSEARCH_HOST
      value: "elasticsearch-svc.nordmart-dev-apps"
    - name: ELASTICSEARCH_PORT
      value: "9200"
    - name: KAFKA_ADDRESS
      value: "kafka-cluster-kafka-bootstrap.nordmart-dev-apps"
    - name: KAFKA_PORT
      value: "9092"
rbac:
  create: false
  serviceAccount:
    name: default
configMap: {}