applicationName: "search"
deployment:
  annotations:
  podLabels:
    app: search
  volumes: {}
  image:
    repository: stakater/search
    tag: v0.0.1
  env:
  - name: ELASTICSEARCH_PASSWORD
    valueFrom:
      secretKeyRef:
        name: elasticsearch-secret
        key: elasticsearch_password
  - name: ELASTICSEARCH_HOST
    value: "elasticsearch-svc.nordmart-dev-apps"
  - name: ELASTICSEARCH_PORT
    value: "9200"
  - name: KAFKA_ADDRESS
    value: "kafka-cluster-kafka-bootstrap.nordmart-dev-apps"
  - name: KAFKA_PORT
    value: "9092"
  - name: JAEGER_ENDPOINT
    value: "http://jaeger-collector.istio-system:14268/api/traces"
  probes:
    readinessProbe:
      failureThreshold: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /actuator/health
        port: 8080
    livenessProbe:
      failureThreshold: 3
      periodSeconds: 60
      successThreshold: 1
      timeoutSeconds: 1
      initialDelaySeconds: 10
      httpGet:
        path: /actuator/health
        port: 8080
service:
  ports:
  - port: 8080
    name: https
    targetPort: 8080
rbac:
  create: false
  serviceAccount:
    name: default
configMap:
  enabled: false
