---
# Source: application/templates/service.yaml

apiVersion: v1
kind: Service
metadata:
  labels:
    app: search
    group: com.stakater.platform
    provider: stakater
    version: "1.0.0"
    chart: "application-0.0.13"
    release: "NAMESPACE_NAME-search"
    heritage: "Tiller"
  name: search
spec:
  selector:
    app: search
    
  ports:
    - name: https
      port: 8080
      targetPort: 8080
    